### ISSUE TITLE
Artifacts for 3.3 missing from GH release page

### ISSUE THREAD

**Issue by Emzi0767** [lavalink-devs/Lavalink#256]
[Release 3.3](https://github.com/Frederikam/Lavalink/releases/tag/3.3) has no JAR artifacts. Is this intentional?

**Comment by freyacodes** [comment]
There seems to be a problem with the build. The CI does not seem to be aware of the tag, so our automated upload script ignores the artifact. 

Maybe it was because the build started before I drafted a release, but even forcing a rebuild did not seem to make the tag appear.

Uploaded manually for now.
