### ISSUE TITLE
Update README for versioning standard

### ISSUE THREAD

**Issue by aikaterna** [lavalink-devs/Lavalink#751]
In https://github.com/freyacodes/Lavalink#versioning-policy there is no definition listed for pre-releases or RC builds and how they fit into the schema. Would there also be a need to consider alpha or beta builds and how to define those differently from an RC or pre-release? 

I feel like the definitions of `api.major.minor.patch` could use a little bit of description too. It's implied that `patch` will be an int based on release history when semantic versioning styles define that there could be characters instead, and someone may expect something like `3.5.0` for a release when the 3.5 release was versioned as `3.5`. 

The reason why I am opening this issue is for cases like implementing a regex match to see if a new Lavalink version is available or other ways to work on auto-updating and/or knowing when a qualified release is available based on the level of use or need (for example, needing a pre-release jar before a full release to push a specific fix to users faster).

**Comment by Jackenmen** [comment]
Based on how the version numbers looked in the past, I imagine that one of these regex patterns (depending on whether you want to future-proof it in case you ever want to do alphas/betas) would describe the used version format well:
![image](https://user-images.githubusercontent.com/6032823/192068731-23b4cfb4-767d-4c08-83ef-2857cbd2c6a2.png)
![image](https://user-images.githubusercontent.com/6032823/192068793-7f7df7a0-1683-4564-933d-a5cc32c33be8.png)

It would be incredibly useful if the full format (including pre-release numbers) were specified in README so that it's more dependable. It wouldn't have to be specified as a regex, it just seemed convenient to me to explain it like this.

**Comment by topi314** [comment]
To give a quick update here
with v3.6.0 Lavalink will use [semver](https://semver.org/)

**Comment by topi314** [comment]
implemented in https://github.com/freyacodes/Lavalink/releases/tag/3.7.0
