### ISSUE TITLE
Is possible to get deezer in lavalink not plugin.

### ISSUE THREAD

**Issue by vkamsingh** [lavalink-devs/Lavalink#835]
Hello, is it possible to get deezer as a platform like soundcloud and youtube in version 4?

**Comment by Drapersniper** [comment]
Due to it being decoupled it is easier and faster to make updates and fixes without having to build a whole new jar, breaking changes as also easier to be implemented due to it being decouple, not to mention the additional support and maintenance burden added to this project if lavascr is merged into (more questions on how to get the blowfish key,  how to get and setup the Spotify project to get the tokens)

I would highly prefer if Lavascr remains separated from lavalink for those reason, makes updates much easier from users (no need to download a whole new jar every time something breaks, changes just download or specify the plug-in in the app yaml)

**Comment by vkamsingh** [comment]
which platform lavasrc load the track for spotify, applemusic and dezzer?

**Comment by topi314** [comment]
lavalink does not provide lavasrc support
wrong repo

**Comment by vkamsingh** [comment]
okaY
