### ISSUE TITLE
Timescale rate/speed below 1.0 makes track end eariler

### ISSUE THREAD

**Issue by cloudwithax** [lavalink-devs/Lavalink#850]
## Description

After this latest update, 3.7.5, the `endTime` parameter was adjusted to be nullable, making it so you have to make all end times be more than 0, or in almost all cases, the length of the track. This produces an adverse effect when playing a track with a rate/speed lower than 1.0, making the track end eariler then usual.

## Version info
**Client used:** 
Pomice 2.2

Output of `java -version`:
```
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
```

Logs:
```
...
2023-03-11 16:35:52.062  INFO 34 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from Pomice/2.2
2023-03-11 16:36:21.300  INFO 34 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=Ck2CLkwFZGk"
2023-03-11 16:36:21.373  INFO 34 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track YRN **(Remix)
```

**Comment by devoxin** [comment]
This is somewhat a known issue. Likewise, if you increase the speed or rate of a track, it would theoretically end later. This is because of the way filters increase the speed, the track's position isn't updated to match. I'd say this is more of a Lavaplayer issue, than a Lavalink one, due to the way `position` is calculated -- it does not seem to take into account any effect audio filters may have on a track's playback speed.

**Comment by cloudwithax** [comment]
I figured. I updated my client to set `None` to the endTime parameter and it fixed the issue of it skipping eariler, but the issue of updating the player position to match that of the filter is still outstanding.

**Comment by topi314** [comment]
I'm gonna close this as it's nothing we can fix in lavalink
